base:
  project: dvc_learn
  random_state: 42
  target_col: TARGET

estimators:
  RandomForestRegressor:
    params:
      max_depth: 20 
      max_features: 0.5 
      min_samples_split: 2 
      n_estimators: 200

